---
- name: Configuring a ftp server
  hosts: ftp-systems
  vars:
    ftp_server_enable: true
    ftp_client_enable: false
  vars_files:
    - user_info.yml 
  tasks:
  - name: CONFIGURING A FTP SERVER
    include_role:
      name: ftp-server
    when: inventory_hostname in groups['ftp-server'] and ftp_server_enable == true

  - name: CONFIGURING A LINUX FTP CLIENT
    include_role:
      name: ftp-client-linux
    when: inventory_hostname in groups['ftp-clients'] and ftp_client_enable == true
  
