---
# tasks file for ftp
- name: INSTALLING A REQUIRED PACKAGES
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"
  notify: restart vsftpd

- name: GENERATING A SSL KEY & CERTIFICATE
  include_tasks: ssl.yml
  when: ssl.ssl_enable is defined and ssl.ssl_enable | lower == "yes"

# Create a user with password
- name: Creating a FTP users
  user:
    name: "{{ item.name }}"
    state: present
    password: "{{ item.pass | string | password_hash('sha512') }}"
  when: item.pass is defined
  loop: "{{ ftp_users }}"
  no_log: yes

# Create a user without password
- name: Creating a FTP users
  user:
    name: "{{ item.name }}"
    state: present
  when: item.pass is not defined
  loop: "{{ ftp_users }}"
  no_log: yes

- name: modifying a /etc/vsftpd/user_list file
  lineinfile:
    path: "{{ userlist.userlist_file }}"
    line: "{{ item.name }}"
    state: present
    create: true
  loop: "{{ ftp_users }}"
  when: userlist.userlist_enable is defined and userlist.userlist_enable | lower == "yes"

- name: Configuring a chroot
  include_tasks: chroot.yml
  when: chroot.chroot_local_user | lower == "yes" or chroot.chroot_list_enable | lower == "yes"

- name: modify a /etc/vsftpd/vsftpd.conf
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify: restart vsftpd

- name: Starting a firewalld
  service:
    name: firewalld
    state: restarted
    enabled: true
  notify: 
    - config firewall rule(ftp)
    - config firewall rule(passive ports)

- name: CONFIGURING A SELINUX
  selinux:
    policy: targeted
    state: permissive



